name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  GH_REPO: ${{github.repository}}
  GH_NO_UPDATE_NOTIFIER: 1
  GH_PROMPT_DISABLED: 1

concurrency:
  group: "tests-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  tap_syntax:
    if: github.repository_owner == 'tenfyzhong'
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    env:
      HOMEBREW_SIMULATE_MACOS_ON_LINUX: 1
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew tap homebrew/test-bot

      - name: Cache style cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Homebrew/style
          key: style-cache-${{ github.sha }}
          restore-keys: style-cache-

      - run: brew test-bot --only-tap-syntax

  tests:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        runner: ["ubuntu-latest", "macos-latest"]
    name: Test - ${{matrix.runner}}
    permissions:
      pull-requests: read
    runs-on: ${{matrix.runner}}
    timeout-minutes: 90
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew tap homebrew/test-bot

      - name: Checkout tap
        run: | 
          brew tap tenfyzhong/tap
          cd $(brew --repository tenfyzhong/tap)
          git checkout ${{github.ref_name}}

      - run: brew test-bot --only-formulae-detect
        id: formulae-detect
      - name: Install formulae
        run: brew install --build-from-source ${{ steps.formulae-detect.outputs.testing_formulae }}
      - name: Test formulae
        run: brew test ${{ steps.formulae-detect.outputs.testing_formulae }}
      - name: Audit formulae
        run: brew audit --strict ${{ steps.formulae-detect.outputs.testing_formulae }}
