name: CI

on:
  pull_request:

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  GH_REPO: ${{github.repository}}
  GH_NO_UPDATE_NOTIFIER: 1
  GH_PROMPT_DISABLED: 1

concurrency:
  group: "tests-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        runner: ["ubuntu-latest", "macos-latest"]
    name: Test - ${{matrix.runner}}
    permissions:
      pull-requests: read
    runs-on: ${{matrix.runner}}
    timeout-minutes: 90
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew tap homebrew/test-bot
          brew tap tenfyzhong/tap

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout tap
        run: | 
          cd $(brew --repository tenfyzhong/tap)
          git remote set-url origin ${{github.repositoryUrl}}
          git pull
          git checkout ${{steps.extract_branch.outputs.branch}}

      - run: brew test-bot --only-formulae-detect
        id: formulae-detect

      - name: Install formulae
        run: brew install --build-from-source ${{ steps.formulae-detect.outputs.testing_formulae }}

      - name: Test formulae
        run: brew test ${{ steps.formulae-detect.outputs.testing_formulae }}

      - name: Audit formulae
        run: brew audit --strict ${{ steps.formulae-detect.outputs.testing_formulae }}
